# Generated by Django 3.2.8 on 2021-11-03 11:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bids_bid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bids',
            constraint=models.CheckConstraint(check=models.Q(('bid__lte', django.db.models.expressions.F('bid'))), name='startbid_greater_than_bid'),
        ),
    ]
