# Generated by Django 3.2.8 on 2021-11-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211103_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[('No Category', 'No Category'), ('Cars', 'Cars'), ('Fathion', 'Fathion'), ('Sport', 'Sport'), ('Electronics', 'Electronics')], default=('No Category', 'No Category'), max_length=12),
        ),
    ]
