# Generated by Django 3.2.8 on 2021-11-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211104_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='active',
        ),
        migrations.AddField(
            model_name='auctions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
